HeadHuntingYourSelf: 'You can''t put an HeadHunting at yourself'
SpecifyAPlayer: 'Please, specify a player'
NotFindPlayer: 'Not find the player'
HeadHuntingOn: 'You put an HeadHunting on '
NotHaveMoney: 'You don''t have enough money'
WasSlainBy: ' Was slain by '