HeadHuntingYourSelf: 'You can''t put an HeadHunting on yourself'
CorrectUsage: 'Use /hunting  <player> <bounty>'
NotFindPlayer: 'Could not find the player'
HeadHuntingOn: 'You put an HeadHunting on %p'
BroadcastHeadHuntingOn: '%s put an HeadHunting on %t with a bounty of %b'
NotHaveMoney: 'You don''t have enough money'
WasSlainBy: '%d was slain by %k! HeadHunting is finished'
NotANumber: 'Please specify a valid bounty'